In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model   import LinearRegression

In [2]:
import pandas as pd


In [3]:
df=pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [4]:
df.columns
df

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [5]:
df.head(10)

name  year  selling_price  km_driven    fuel  \
0              Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2       Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3     Datsun RediGO T Option  2017         250000      46000  Petrol   
4      Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   
5       Maruti Alto LX BSIII  2007         140000     125000  Petrol   
6  Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol   
7   Tata Indigo Grand Petrol  2014         240000      60000  Petrol   
8   Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol   
9   Maruti Celerio Green VXI  2017         365000      78000     CNG   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  
5  Individual       Manual   First Owner  
6  Individual       Manual   First Owner  
7  Individual       Manual  Second Owner  
8  Individual       Manual   First Owner  
9  Individual       Manual   First Owner

In [6]:
df.tail(10)

name  year  selling_price  \
4330                Tata Indica Vista Aqua 1.4 TDI  2010         150000   
4331          Ford EcoSport 1.5 TDCi Titanium BSIV  2015         530000   
4332                  Mahindra Scorpio S2 7 Seater  2015         750000   
4333                               Maruti Ritz VDi  2012         225000   
4334  Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV  2012         600000   
4335           Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999   
4336                    Hyundai i20 Magna 1.4 CRDi  2014         409999   
4337                           Maruti 800 AC BSIII  2009         110000   
4338              Hyundai Creta 1.6 CRDi SX Option  2016         865000   
4339                              Renault KWID RXT  2016         225000   

      km_driven    fuel seller_type transmission         owner  
4330     130000  Diesel  Individual       Manual  Second Owner  
4331     175000  Diesel  Individual       Manual   Third Owner  
4332     120000  Diesel  Individual       Manual   First Owner  
4333      90000  Diesel  Individual       Manual  Second Owner  
4334     170000  Diesel  Individual       Manual   First Owner  
4335      80000  Diesel  Individual       Manual  Second Owner  
4336      80000  Diesel  Individual       Manual  Second Owner  
4337      83000  Petrol  Individual       Manual  Second Owner  
4338      90000  Diesel  Individual       Manual   First Owner  
4339      40000  Petrol  Individual       Manual   First Owner

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [8]:
df.describe()

year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [9]:
df.shape

(4340, 8)

In [10]:
df.isnull()

name   year  selling_price  km_driven   fuel  seller_type  \
0     False  False          False      False  False        False   
1     False  False          False      False  False        False   
2     False  False          False      False  False        False   
3     False  False          False      False  False        False   
4     False  False          False      False  False        False   
...     ...    ...            ...        ...    ...          ...   
4335  False  False          False      False  False        False   
4336  False  False          False      False  False        False   
4337  False  False          False      False  False        False   
4338  False  False          False      False  False        False   
4339  False  False          False      False  False        False   

      transmission  owner  
0            False  False  
1            False  False  
2            False  False  
3            False  False  
4            False  False  
...            ...    ...  
4335         False  False  
4336         False  False  
4337         False  False  
4338         False  False  
4339         False  False  

[4340 rows x 8 columns]

In [11]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["name"]=le.fit_transform(df["name"])
df["fuel"]=le.fit_transform(df["fuel"])
df["seller_type"]=le.fit_transform(df["seller_type"])
df["transmission"]=le.fit_transform(df["transmission"])
df["owner"]=le.fit_transform(df["owner"])
df

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0      775  2007          60000      70000     4            1             1   
1     1041  2007         135000      50000     4            1             1   
2      505  2012         600000     100000     1            1             1   
3      118  2017         250000      46000     4            1             1   
4      279  2014         450000     141000     1            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
4335   602  2014         409999      80000     1            1             1   
4336   601  2014         409999      80000     1            1             1   
4337   777  2009         110000      83000     4            1             1   
4338   381  2016         865000      90000     1            1             1   
4339  1154  2016         225000      40000     4            1             1   

      owner  
0         0  
1         0  
2         0  
3         0  
4         2  
...     ...  
4335      2  
4336      2  
4337      2  
4338      0  
4339      0  

[4340 rows x 8 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   int64
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   int64
 5   seller_type    4340 non-null   int64
 6   transmission   4340 non-null   int64
 7   owner          4340 non-null   int64
dtypes: int64(8)
memory usage: 271.4 KB


In [15]:
df.duplicated().sum()

np.int64(763)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
x=df.drop(["selling_price"],axis=1)
x

name  year  km_driven  fuel  seller_type  transmission  owner
0      775  2007      70000     4            1             1      0
1     1041  2007      50000     4            1             1      0
2      505  2012     100000     1            1             1      0
3      118  2017      46000     4            1             1      0
4      279  2014     141000     1            1             1      2
...    ...   ...        ...   ...          ...           ...    ...
4335   602  2014      80000     1            1             1      2
4336   601  2014      80000     1            1             1      2
4337   777  2009      83000     4            1             1      2
4338   381  2016      90000     1            1             1      0
4339  1154  2016      40000     4            1             1      0

[3577 rows x 7 columns]

In [18]:
y=df["selling_price"]
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 3577, dtype: int64

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x



array([[ 0.0465849 , -1.40256584,  0.01575368, ...,  0.45738437,
         0.30912612, -0.70888558],
       [ 0.71648628, -1.40256584, -0.4046503 , ...,  0.45738437,
         0.30912612, -0.70888558],
       [-0.63339019, -0.22641758,  0.64635965, ...,  0.45738437,
         0.30912612, -0.70888558],
       ...,
       [ 0.05162175, -0.93210654,  0.28901627, ...,  0.45738437,
         0.30912612,  0.85731808],
       [-0.94567504,  0.71450103,  0.43615766, ...,  0.45738437,
         0.30912612, -0.70888558],
       [ 1.00106845,  0.71450103, -0.61485229, ...,  0.45738437,
         0.30912612, -0.70888558]], shape=(3577, 7))

In [20]:
 from sklearn.model_selection import train_test_split
 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
 print(x_train.shape)
 print(x_test.shape)
 print(y_train.shape)
 print(y_test.shape)
 from sklearn.linear_model import LinearRegression
 lr=LinearRegression()
 lr.fit(x_train,y_train)
 y_pred=lr.predict(x_test)
 y_pred

(2861, 7)
(716, 7)
(2861,)
(716,)


array([ 4.90229693e+05,  4.67545283e+05,  5.92765884e+05,  1.54363213e+06,
        6.00219042e+04,  3.27109381e+05,  1.35386780e+05,  6.84839203e+05,
        7.86263343e+05,  3.39578066e+05,  5.01051121e+05,  3.87839895e+05,
        7.11066643e+05,  2.67662348e+05,  4.98463941e+05,  4.19041350e+05,
        3.59148996e+05,  7.77119838e+05,  4.57521400e+05,  3.14831637e+05,
        1.59483742e+05,  2.19279808e+05,  7.45235903e+02,  5.78964999e+05,
        5.41200060e+05,  7.99700990e+05,  5.01691259e+05,  6.46560524e+05,
        5.76293229e+05,  1.34800768e+05,  5.82404423e+05,  9.24009346e+04,
        7.98285974e+04,  1.23534160e+06,  2.70923153e+05,  7.36974286e+04,
        3.91694274e+05,  2.70346644e+05,  5.13289685e+05,  7.39286235e+05,
        1.33456049e+06,  4.11662167e+05,  7.46965677e+05,  7.05320586e+05,
        4.42738614e+05,  1.99183614e+05,  1.55967006e+05,  3.76586184e+05,
        1.16291721e+05,  4.55005231e+05,  3.50367710e+05,  5.63522993e+05,
        7.06649992e+05,  

In [21]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.3845301161683755
198263378271.34103


In [22]:
 from sklearn.linear_model import LinearRegression
 lr=LinearRegression()
 lr.fit(x_test,y_test)
 y_pred=lr.predict(x_test)
 y_pred

array([ 5.16274892e+05,  5.64386339e+05,  6.25895459e+05,  1.68406245e+06,
        3.50923133e+04,  2.99690523e+05,  1.22975235e+05,  6.86579209e+05,
        8.93206661e+05,  2.81033842e+05,  4.25824717e+05,  3.66918417e+05,
        7.37867281e+05,  3.12145589e+05,  4.90718984e+05,  4.09788174e+05,
        3.39729397e+05,  8.10577578e+05,  4.86982328e+05,  4.04869355e+05,
        1.72745914e+05,  1.92512120e+05,  2.83978787e+04,  5.52356916e+05,
        5.51916875e+05,  8.35480357e+05,  5.14679066e+05,  5.81443017e+05,
        5.97859420e+05,  1.09620978e+05,  6.02013551e+05,  8.79075773e+04,
        9.57864320e+04,  1.23946969e+06,  2.58310725e+05,  1.39926834e+04,
        4.48569241e+05,  2.66055351e+05,  4.22777442e+05,  7.85927188e+05,
        1.32880950e+06,  4.91285070e+05,  8.32021484e+05,  7.81880855e+05,
        4.22394290e+05,  2.87222331e+05,  1.24271571e+05,  3.56877152e+05,
        6.03226976e+04,  4.26500963e+05,  3.29053242e+05,  6.53009567e+05,
        6.82475029e+05,  

In [23]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.39451233539907715
195047772505.21802


In [24]:
 from sklearn.tree import DecisionTreeRegressor
 dr=DecisionTreeRegressor()
 dr.fit(x_train,y_train)
 y_pred=dr.predict(x_test)
 y_pred

array([ 395000. ,  455000. ,  919999. ,  975000. ,  350000. ,  300000. ,
        145000. ,  700000. ,  700000. ,  390000. ,  120000. ,  480000. ,
        680000. ,  229999. ,  350000. ,  600000. ,  300000. ,  900000. ,
        500000. ,  280000. ,  110000. ,  229999. ,   80000. ,  660000. ,
        300000. ,  475000. ,  450000. ,  655000. ,  450000. ,  120000. ,
        800000. ,  195000. ,  175000. ,  800000. ,  300000. ,  145000. ,
        350000. ,  210000. ,  750000. , 1450000. ,  720000. ,  100000. ,
        675000. ,  495000. ,  550000. ,  210000. ,  300000. ,  260000. ,
        350000. ,  475000. ,  300000. ,  600000. ,  655000. ,  400000. ,
        200999. ,  500000. ,  280000. ,  250000. ,  550000. ,  550000. ,
        360000. ,  180000. ,   90000. ,  150000. ,  325000. ,  325000. ,
        500000. , 1735000. ,  475000. ,  150000. , 1334000. ,  110000. ,
        450000. ,  325000. ,  250000. ,  607500. ,  250000. ,  200000. ,
         73000. ,   45000. ,  490000. ,  220000. , 

In [25]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.18078269659553292
263897218008.70706


In [26]:
 from sklearn.tree import DecisionTreeRegressor
 dr=DecisionTreeRegressor()
 dr.fit(x_test,y_test)
 y_pred=dr.predict(x_test)
 y_pred

array([ 270000.,  525000.,  990000., 3800000.,  229999.,  325000.,
        210000.,  500000.,  790000.,  360000.,  250000.,  160000.,
        500000.,  229999.,  360000.,  612000.,  350000.,  800000.,
        160000.,  330000.,  180000.,  400000.,  150000.,  525000.,
        300000.,  409999.,  495000.,  628000.,  500000.,  110000.,
       1050000.,  100000.,   75000.,  509999.,  290000.,  114999.,
        350000.,  650000.,  800000., 1400000.,  738000.,  170000.,
        600000.,  400000.,  650000.,  265000.,  150000.,  350000.,
        320000.,  500000.,  229999.,  500000.,  700000.,  300000.,
        430000.,  425000.,  250000.,  281000.,  315000.,  350000.,
        260000.,  150000.,   75000.,  120000.,  635000.,  385000.,
        380000., 1300000.,  320000.,  270000., 1331000.,  300000.,
        260000.,  200000.,  200000.,  750000.,  150000.,  428000.,
        175000.,   43000.,  610000.,  305000.,  225000.,  625000.,
        430000.,  730000.,  434999.,  300000.,  325000.,  5000

In [27]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.9999878060667396
3928072.625698324


In [28]:
 from sklearn.ensemble import RandomForestRegressor
 rf=RandomForestRegressor()
 rf.fit(x_train,y_train)
 y_pred=rf.predict(x_test)
 y_pred

array([ 390250.        ,  478939.98      , 1080769.78      ,
       1566520.        ,  197799.99      ,  313863.26333333,
        162450.        ,  624200.        ,  935959.89      ,
        385049.97      ,  145830.        ,  359839.95      ,
        706850.        ,  234539.7       ,  343949.99      ,
        555339.99      ,  351399.97      , 1136249.99      ,
        301433.32333333,  314459.96      ,  149259.87      ,
        298259.87      ,   92950.        ,  555739.97      ,
        337930.        ,  507120.        ,  401210.        ,
        646340.        ,  406689.9       ,  152939.89      ,
        558419.98      ,  149589.98      ,  124869.99      ,
        524650.        ,  248350.        ,  187500.        ,
        361439.89      ,  232749.99      ,  657750.        ,
       1333650.        ,  776349.98      ,  131910.        ,
        708660.        ,  554549.98      ,  555033.32333333,
        234119.97      ,  287169.85      ,  274540.        ,
        222953.33333333,

In [29]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.5234629721016775
153508471339.52176


In [30]:
 from sklearn.ensemble import RandomForestRegressor
 rf=RandomForestRegressor()
 rf.fit(x_test,y_test)
 y_pred=rf.predict(x_test)
 y_pred

array([ 324509.98      ,  504570.        ,  945380.        ,
       3601500.        ,  213949.39      ,  295109.91      ,
        191979.99      ,  506600.        ,  872439.99      ,
        371770.        ,  220550.        ,  195349.99      ,
        596550.        ,  233129.23      ,  338459.99      ,
        534310.        ,  353600.        ,  835150.        ,
        210549.99      ,  336460.        ,  176750.        ,
        394389.99      ,  134050.        ,  583139.99      ,
        332299.99      ,  627419.48      ,  474390.        ,
        650640.        ,  470649.99      ,  119350.        ,
        811789.99      ,  129239.99      ,  102760.        ,
        510249.37      ,  322650.        ,  134429.34      ,
        370989.98      ,  512350.        ,  696499.99      ,
       1220200.        , 1745150.        ,  172000.        ,
        628009.99      ,  484109.98      ,  580400.        ,
        260790.        ,  192300.        ,  333299.95      ,
        257549.94      ,

In [31]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.9279523241960743
23208959490.522358


In [32]:
 from sklearn.neighbors import KNeighborsRegressor
 Knn=KNeighborsRegressor()
 Knn.fit(x_train,y_train)
 y_pred=Knn.predict(x_test)
 y_pred

array([ 669000. ,  433000. , 1146000. , 1035800. ,  181000. ,  431000. ,
        158000. ,  694000. , 1009200. ,  314000. ,  201000. ,  441000. ,
        677999.8,  289400. ,  407999.6,  516200. ,  295000. , 1048000. ,
        316000. ,  311800. ,  167999.8,  300600. ,   97000. ,  438000. ,
        502000. ,  566400. ,  404000. ,  633800. ,  375999.8,  155999.8,
        610000. ,  185999.8,  139000. ,  640000. ,  294000. ,  160000. ,
        421000. ,  259999.8,  444800. , 1146000. ,  754000. ,  559000. ,
        847800. ,  764800. ,  408999.6,  192200. ,  283600. ,  284000. ,
        126000. ,  465000. ,  247000. ,  343199.8,  534000. ,  446000. ,
        128800. ,  734000. ,  359000. ,  384200. ,  491400. ,  400800. ,
        326000. ,  376400. ,  262000. ,  150999.8,  406000. ,  361200. ,
        450000. , 1934000. ,  515600. ,  222000. ,  996399.8,  378000. ,
        411000. ,  464000. ,  533000. ,  636000. ,  207599.8,  519000. ,
        100000. ,   61000. ,  495000. ,  257600. , 

In [33]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.35087175668780934
209105858517.72443


In [34]:
 from sklearn.neighbors import KNeighborsRegressor
 Knn=KNeighborsRegressor()
 Knn.fit(x_test,y_test)
 y_pred=Knn.predict(x_test)
 y_pred

array([ 361399.8,  346600. ,  527000. , 4065200. ,  194999.8,  401000. ,
        245000. ,  626200. ,  852000. ,  307000. ,  227000. ,  340000. ,
        756000. ,  219999.8,  409000. ,  513400. ,  378000. ,  859000. ,
        500000. ,  316000. ,  183800. ,  358000. ,  110000. ,  570200. ,
        561199.8,  707999.8,  396600. ,  632600. ,  595000. ,  168000. ,
        702000. ,  153200. ,  120800. ,  485999.8,  368000. ,  158999.8,
        309000. ,  376000. ,  519000. , 1160000. ,  632600. ,  399000. ,
        724000. ,  664000. ,  349000. ,  312999.8,  210000. ,  317000. ,
        165000. ,  480999.8,  312999.8,  476000. ,  810000. ,  272000. ,
        263000. ,  539800. ,  269000. ,  451200. ,  409000. ,  362999.8,
        503000. ,  289000. ,  174999.8,  139000. ,  471999.8,  444000. ,
        314000. , 1598000. ,  566000. ,  289999.8,  979999.8,  310199.8,
        296000. ,  299000. ,  569000. ,  574000. ,  163600. ,  274800. ,
        109000. ,   70400. ,  436800. ,  232000. , 

In [35]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


0.634017738958591
117895093436.13016


In [36]:
 from sklearn.svm import SVR
 svr=SVR()
 svr.fit(x_test,y_test)
 y_pred=svr.predict(x_test)
 y_pred

array([350010.57093933, 350003.42825645, 350006.17648622, 350013.55904824,
       349912.5392177 , 349958.4214034 , 349932.17476191, 350034.18642245,
       350037.2764293 , 349963.39540133, 349994.98089512, 349974.87299975,
       350047.57688306, 349960.90141313, 349984.71945307, 350000.12477343,
       349974.44012967, 350055.56344851, 350000.45183646, 349983.81974085,
       349930.72807518, 349938.03080915, 349904.55877662, 350019.66064568,
       350014.03173896, 350051.76518494, 349988.84701013, 350026.23107449,
       350018.29552377, 349909.52063494, 350025.13405005, 349907.02548727,
       349920.22944525, 350013.69581702, 349944.87321523, 349935.01383412,
       349999.90000001, 349946.65429257, 350000.62137766, 350052.55189532,
       350014.05753497, 349993.73463848, 350034.43244175, 350031.86494874,
       349972.34512545, 349966.0792833 , 349918.68912312, 349989.04584628,
       349931.47191362, 350002.41371797, 349958.96461445, 350002.14347083,
       350044.47994243, 3

In [37]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


-0.05450975991233986
339692766311.7262


In [38]:
 from sklearn.svm import SVR
 svr=SVR()
 svr.fit(x_train,y_train)
 y_pred=svr.predict(x_test)
 y_pred

array([350060.51354725, 350056.56000058, 350054.33884857, 350067.32151595,
       349692.13663195, 349851.02437981, 349773.8216917 , 350128.69537324,
       350165.25118524, 349863.70617073, 349983.96864752, 349926.01951707,
       350203.01955119, 349895.97894618, 349956.8486682 , 350012.14888621,
       349913.99413319, 350218.86247036, 350015.84674514, 349982.36835724,
       349783.16700861, 349801.02826089, 349681.20329067, 350097.04470472,
       350078.1098905 , 350213.61925241, 349982.5430069 , 350109.5918114 ,
       350078.34170566, 349694.03510407, 350118.37756989, 349680.23469179,
       349746.81881747, 350062.84974887, 349825.69222649, 349766.80038071,
       350012.78420634, 349833.4195476 , 350010.28911161, 350213.07622885,
       350063.81807283, 350014.45236013, 350148.79543102, 350139.49856055,
       349912.26149088, 349885.31740774, 349729.1098024 , 349952.61463542,
       349764.67506222, 350013.53425848, 349861.06554794, 350031.20392304,
       350180.7643007 , 3

In [39]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print(r2)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)


-0.05437687521197487
339649959717.4361
